In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.io.wavfile as wav


In [2]:
import glob as glob

In [3]:
import librosa

In [4]:
!pip install python_speech_features
from python_speech_features import mfcc


  Created wheel for python-speech-features: filename=python_speech_features-0.6-cp36-none-any.whl size=5890 sha256=00638968ac9e2a7e7361f22196cd1c893208a7f07a4aa19d569a35e63e8a154c
  Stored in directory: /root/.cache/pip/wheels/3c/42/7c/f60e9d1b40015cd69b213ad90f7c18a9264cd745b9888134be
Successfully built python-speech-features


In [ ]:
train_audio=glob.glob('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/TRAIN/*')

In [ ]:
len(train_audio)

250

In [ ]:
rate=[]
signals=[]
j=0
max=0
for i in train_audio:
  (rat,sig) = wav.read(i)
  rate.append(rat)
  signals.append(sig)
  if max<len(sig):
    max=len(sig)
  print(max)
  print(j)
  j=j+1


In [ ]:
mfccs=[]
for j in range(0,250):
  mfcc1=mfcc(signals[j],rate[j],winlen=0.1,winfunc=np.hamming,winstep=0.05,numcep=13,appendEnergy=True,highfreq=8000)
  print(np.shape(mfcc1))
  delta=librosa.feature.delta(mfcc1)
  accerlation=librosa.feature.delta(mfcc1,order=2)
  print(np.shape(delta))
  print(np.shape(accerlation))
  print("\n")
  mfcc1=np.append(mfcc1,delta,axis=1)
  mfcc1=np.append(mfcc1,accerlation,axis=1)
  mfccs.append(mfcc1)

(101, 13)
(101, 13)
(101, 13)


(67, 13)
(67, 13)
(67, 13)


(103, 13)
(103, 13)
(103, 13)


(153, 13)
(153, 13)
(153, 13)


(90, 13)
(90, 13)
(90, 13)


(103, 13)
(103, 13)
(103, 13)


(102, 13)
(102, 13)
(102, 13)


(95, 13)
(95, 13)
(95, 13)


(90, 13)
(90, 13)
(90, 13)




(89, 13)
(89, 13)
(89, 13)


(100, 13)
(100, 13)
(100, 13)


(95, 13)
(95, 13)
(95, 13)


(102, 13)
(102, 13)
(102, 13)


(79, 13)
(79, 13)
(79, 13)


(103, 13)
(103, 13)
(103, 13)


(92, 13)
(92, 13)
(92, 13)


(129, 13)
(129, 13)
(129, 13)


(86, 13)
(86, 13)
(86, 13)




(149, 13)
(149, 13)
(149, 13)


(112, 13)
(112, 13)
(112, 13)


(115, 13)
(115, 13)
(115, 13)


(98, 13)
(98, 13)
(98, 13)


(112, 13)
(112, 13)
(112, 13)


(90, 13)
(90, 13)
(90, 13)


(99, 13)
(99, 13)
(99, 13)


(67, 13)
(67, 13)
(67, 13)


(118, 13)
(118, 13)
(118, 13)




(82, 13)
(82, 13)
(82, 13)


(99, 13)
(99, 13)
(99, 13)


(120, 13)
(120, 13)
(120, 13)


(79, 13)
(79, 13)
(79, 13)


(92, 13)
(92, 13)
(92, 13)


(120, 13)
(120, 13)
(120, 13)


(131, 13)
(131, 13)
(131, 13)


(87, 13)
(87, 13)
(87, 13)


(87, 13)
(87, 13)
(87, 13)




(94, 13)
(94, 13)
(94, 13)


(112, 13)
(112, 13)
(112, 13)


(94, 13)
(94, 13)
(94, 13)


(146, 13)
(146, 13)
(146, 13)


(92, 13)
(92, 13)
(92, 13)


(106, 13)
(106, 13)
(106, 13)


(129, 13)
(129, 13)
(129, 13)


(107, 13)
(107, 13)
(107, 13)




(136, 13)
(136, 13)
(136, 13)


(97, 13)
(97, 13)
(97, 13)


(109, 13)
(109, 13)
(109, 13)


(98, 13)
(98, 13)
(98, 13)


(85, 13)
(85, 13)
(85, 13)


(105, 13)
(105, 13)
(105, 13)


(87, 13)
(87, 13)
(87, 13)


(89, 13)
(89, 13)
(89, 13)


(103, 13)
(103, 13)
(103, 13)




(90, 13)
(90, 13)
(90, 13)


(67, 13)
(67, 13)
(67, 13)


(105, 13)
(105, 13)
(105, 13)


(112, 13)
(112, 13)
(112, 13)


(117, 13)
(117, 13)
(117, 13)


(123, 13)
(123, 13)
(123, 13)


(100, 13)
(100, 13)
(100, 13)


(87, 13)
(87, 13)
(87, 13)


(90, 13)
(90, 13)
(90, 13)




(95, 13)
(95, 13)
(95, 13)


(95, 13)
(95, 13)
(95, 13)


(91, 13)
(91, 13)
(91, 13)


(109, 13)
(109, 13)
(109, 13)


(101, 13)
(101, 13)
(101, 13)


(150, 13)
(150, 13)
(150, 13)


(130, 13)
(130, 13)
(130, 13)


(98, 13)
(98, 13)
(98, 13)


(84, 13)
(84, 13)
(84, 13)




(89, 13)
(89, 13)
(89, 13)


(94, 13)
(94, 13)
(94, 13)


(142, 13)
(142, 13)
(142, 13)


(102, 13)
(102, 13)
(102, 13)


(123, 13)
(123, 13)
(123, 13)


(109, 13)
(109, 13)
(109, 13)


(103, 13)
(103, 13)
(103, 13)


(103, 13)
(103, 13)
(103, 13)


(87, 13)
(87, 13)
(87, 13)




(85, 13)
(85, 13)
(85, 13)


(103, 13)
(103, 13)
(103, 13)


(99, 13)
(99, 13)
(99, 13)


(112, 13)
(112, 13)
(112, 13)


(79, 13)
(79, 13)
(79, 13)


(142, 13)
(142, 13)
(142, 13)


(137, 13)
(137, 13)
(137, 13)


(107, 13)
(107, 13)
(107, 13)


(130, 13)
(130, 13)
(130, 13)




(108, 13)
(108, 13)
(108, 13)


(80, 13)
(80, 13)
(80, 13)


(108, 13)
(108, 13)
(108, 13)


(157, 13)
(157, 13)
(157, 13)


(100, 13)
(100, 13)
(100, 13)


(115, 13)
(115, 13)
(115, 13)


(129, 13)
(129, 13)
(129, 13)


(138, 13)
(138, 13)
(138, 13)




(113, 13)
(113, 13)
(113, 13)


(86, 13)
(86, 13)
(86, 13)


(98, 13)
(98, 13)
(98, 13)


(107, 13)
(107, 13)
(107, 13)


(79, 13)
(79, 13)
(79, 13)


(103, 13)
(103, 13)
(103, 13)


(149, 13)
(149, 13)
(149, 13)


(111, 13)
(111, 13)
(111, 13)


(82, 13)
(82, 13)
(82, 13)




(92, 13)
(92, 13)
(92, 13)


(126, 13)
(126, 13)
(126, 13)


(157, 13)
(157, 13)
(157, 13)


(112, 13)
(112, 13)
(112, 13)


(102, 13)
(102, 13)
(102, 13)


(98, 13)
(98, 13)
(98, 13)


(120, 13)
(120, 13)
(120, 13)


(94, 13)
(94, 13)
(94, 13)




(99, 13)
(99, 13)
(99, 13)


(107, 13)
(107, 13)
(107, 13)


(111, 13)
(111, 13)
(111, 13)


(95, 13)
(95, 13)
(95, 13)


(110, 13)
(110, 13)
(110, 13)


(106, 13)
(106, 13)
(106, 13)


(146, 13)
(146, 13)
(146, 13)


(90, 13)
(90, 13)
(90, 13)


(103, 13)
(103, 13)
(103, 13)




(154, 13)
(154, 13)
(154, 13)


(91, 13)
(91, 13)
(91, 13)


(111, 13)
(111, 13)
(111, 13)


(123, 13)
(123, 13)
(123, 13)


(110, 13)
(110, 13)
(110, 13)


(118, 13)
(118, 13)
(118, 13)


(94, 13)
(94, 13)
(94, 13)


(90, 13)
(90, 13)
(90, 13)


(101, 13)
(101, 13)
(101, 13)




(126, 13)
(126, 13)
(126, 13)


(146, 13)
(146, 13)
(146, 13)


(95, 13)
(95, 13)
(95, 13)


(110, 13)
(110, 13)
(110, 13)


(120, 13)
(120, 13)
(120, 13)


(70, 13)
(70, 13)
(70, 13)


(131, 13)
(131, 13)
(131, 13)


(111, 13)
(111, 13)
(111, 13)


(94, 13)
(94, 13)
(94, 13)


(90, 13)
(90, 13)
(90, 13)




(123, 13)
(123, 13)
(123, 13)


(110, 13)
(110, 13)
(110, 13)


(115, 13)
(115, 13)
(115, 13)


(90, 13)
(90, 13)
(90, 13)


(150, 13)
(150, 13)
(150, 13)


(103, 13)
(103, 13)
(103, 13)


(84, 13)
(84, 13)
(84, 13)


(112, 13)
(112, 13)
(112, 13)


(130, 13)
(130, 13)
(130, 13)




(106, 13)
(106, 13)
(106, 13)


(112, 13)
(112, 13)
(112, 13)


(95, 13)
(95, 13)
(95, 13)


(115, 13)
(115, 13)
(115, 13)


(96, 13)
(96, 13)
(96, 13)


(98, 13)
(98, 13)
(98, 13)


(86, 13)
(86, 13)
(86, 13)


(89, 13)
(89, 13)
(89, 13)


(108, 13)
(108, 13)
(108, 13)


(89, 13)
(89, 13)
(89, 13)




(89, 13)
(89, 13)
(89, 13)


(127, 13)
(127, 13)
(127, 13)


(103, 13)
(103, 13)
(103, 13)


(87, 13)
(87, 13)
(87, 13)


(70, 13)
(70, 13)
(70, 13)


(87, 13)
(87, 13)
(87, 13)


(99, 13)
(99, 13)
(99, 13)


(103, 13)
(103, 13)
(103, 13)


(96, 13)
(96, 13)
(96, 13)


(112, 13)
(112, 13)
(112, 13)




(153, 13)
(153, 13)
(153, 13)


(95, 13)
(95, 13)
(95, 13)


(89, 13)
(89, 13)
(89, 13)


(94, 13)
(94, 13)
(94, 13)


(108, 13)
(108, 13)
(108, 13)


(86, 13)
(86, 13)
(86, 13)


(129, 13)
(129, 13)
(129, 13)


(131, 13)
(131, 13)
(131, 13)


(86, 13)
(86, 13)
(86, 13)




(103, 13)
(103, 13)
(103, 13)


(86, 13)
(86, 13)
(86, 13)


(95, 13)
(95, 13)
(95, 13)


(157, 13)
(157, 13)
(157, 13)


(108, 13)
(108, 13)
(108, 13)


(112, 13)
(112, 13)
(112, 13)


(123, 13)
(123, 13)
(123, 13)


(102, 13)
(102, 13)
(102, 13)


(150, 13)
(150, 13)
(150, 13)




(120, 13)
(120, 13)
(120, 13)


(120, 13)
(120, 13)
(120, 13)


(149, 13)
(149, 13)
(149, 13)


(84, 13)
(84, 13)
(84, 13)


(98, 13)
(98, 13)
(98, 13)


(95, 13)
(95, 13)
(95, 13)


(96, 13)
(96, 13)
(96, 13)


(90, 13)
(90, 13)
(90, 13)


(90, 13)
(90, 13)
(90, 13)


(120, 13)
(120, 13)
(120, 13)




(117, 13)
(117, 13)
(117, 13)


(89, 13)
(89, 13)
(89, 13)


(120, 13)
(120, 13)
(120, 13)


(105, 13)
(105, 13)
(105, 13)


(94, 13)
(94, 13)
(94, 13)


(92, 13)
(92, 13)
(92, 13)


(86, 13)
(86, 13)
(86, 13)


(79, 13)
(79, 13)
(79, 13)


(154, 13)
(154, 13)
(154, 13)


(107, 13)


(107, 13)
(107, 13)


(95, 13)
(95, 13)
(95, 13)


(112, 13)
(112, 13)
(112, 13)


(146, 13)
(146, 13)
(146, 13)


(92, 13)
(92, 13)
(92, 13)


(142, 13)
(142, 13)
(142, 13)


(80, 13)
(80, 13)
(80, 13)


(112, 13)
(112, 13)
(112, 13)


(99, 13)
(99, 13)
(99, 13)




(90, 13)
(90, 13)
(90, 13)


(112, 13)
(112, 13)
(112, 13)


(118, 13)
(118, 13)
(118, 13)


(103, 13)
(103, 13)
(103, 13)


(103, 13)
(103, 13)
(103, 13)


(94, 13)
(94, 13)
(94, 13)


(113, 13)
(113, 13)
(113, 13)


(101, 13)
(101, 13)
(101, 13)


(95, 13)
(95, 13)
(95, 13)




(123, 13)
(123, 13)
(123, 13)


(108, 13)
(108, 13)
(108, 13)


(103, 13)
(103, 13)
(103, 13)


(89, 13)
(89, 13)
(89, 13)


(92, 13)
(92, 13)
(92, 13)


(112, 13)
(112, 13)
(112, 13)


(111, 13)
(111, 13)
(111, 13)


(106, 13)
(106, 13)
(106, 13)


(95, 13)
(95, 13)
(95, 13)


(90, 13)


(90, 13)
(90, 13)


(99, 13)
(99, 13)
(99, 13)


(92, 13)
(92, 13)
(92, 13)


(99, 13)
(99, 13)
(99, 13)


(67, 13)
(67, 13)
(67, 13)


(106, 13)
(106, 13)
(106, 13)


(92, 13)
(92, 13)
(92, 13)


(109, 13)
(109, 13)
(109, 13)


(87, 13)
(87, 13)
(87, 13)


(136, 13)
(136, 13)
(136, 13)




(82, 13)
(82, 13)
(82, 13)


(91, 13)
(91, 13)
(91, 13)


(113, 13)
(113, 13)
(113, 13)


(95, 13)
(95, 13)
(95, 13)


(112, 13)
(112, 13)
(112, 13)




In [ ]:
len(mfccs)

250

In [ ]:
np.shape(mfccs[0])

(101, 39)

In [ ]:
np.save('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/mfccs.npy',mfccs)

/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [18]:
df=pd.read_csv('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/TRAIN.csv')

In [ ]:
df

Filename     Class
0    346.wav  Negative
1    163.wav   Neutral
2    288.wav  Negative
3    279.wav  Negative
4    244.wav  Negative
..       ...       ...
245  204.wav   Neutral
246   46.wav  Positive
247  318.wav  Negative
248   49.wav  Positive
249  191.wav   Neutral

[250 rows x 2 columns]

In [ ]:
names=[]
for i in train_audio:
  temp=i.split(sep="/")
  names.append(temp[6])

In [ ]:
len(names)

250

In [ ]:
names[0]

'122.wav'

In [ ]:
train_audio[0]

'/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/TRAIN/122.wav'

In [14]:
import pickle

In [ ]:

with open("/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/names.txt", "wb") as fp:
  pickle.dump(names, fp)


In [15]:
with open("/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/names.txt", "rb") as fp:
  b = pickle.load(fp)

In [25]:
y_train=[]
emotion={}
emotion['Negative']=np.array([1.,0.,0.])
emotion['Neutral']=np.array([0.,1.,0.])
emotion['Positive']=np.array([0.,0.,1.])


In [26]:
emo={}
for i in range(0,250):
  emo[df.iloc[i,0]]=df.iloc[i,1]

In [27]:
y_train=[]
for i in b:
  try:
    y_train.append(emo[i])
  except:
    print(i)

In [28]:
y_tr=[]
for i in y_train:
  y_tr.append(emotion[i])

In [29]:
y_tr

[array([0., 1., 0.]),
 array([1., 0., 0.]),
 array([0., 0., 1.]),
 array([0., 1., 0.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([1., 0., 0.]),
 array([1., 0., 0.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 1., 0.]),
 array([0., 1., 0.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([1., 0., 0.]),
 array([0., 0., 1.]),
 array([0., 0., 1.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([1., 0., 0.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([0., 0., 1.]),
 array([0., 1., 0.]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 1., 0.]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([0., 0., 1.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 array([0., 1., 0.]),
 array([0., 1., 0.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([0.

In [ ]:
np.save('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/y_train.npy',y_train)

In [ ]:
test_audio=glob.glob('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/TEST/*')

In [ ]:
rate=[]
signals=[]
j=0
max=0
for i in test_audio:
  (rat,sig) = wav.read(i)
  rate.append(rat)
  signals.append(sig)
  if max<len(sig):
    max=len(sig)
  print(max)
  print(j)
  j=j+1

114048
0
116352
1
116352
2
116352
3
120960
4
120960
5
120960
6
120960
7
120960
8
135936
9
135936
10
135936
11
135936
12
161280
13
161280
14
161280
15
161280
16
161280
17
161280
18
161280
19
161280
20
161280
21
161280
22
161280
23
161280
24
161280
25
161280
26
161280
27
161280
28
161280
29
161280
30
161280
31
161280
32
161280
33
161280
34
161280
35
161280
36
161280
37
161280
38
161280
39
161280
40
161280
41
161280
42
161280
43
161280
44
161280
45
161280
46
169344
47
169344
48
169344
49
169344
50
169344
51
169344
52
169344
53
169344
54
169344
55
169344
56
169344
57
169344
58
169344
59
169344
60
169344
61
169344
62
169344
63
169344
64
169344
65
169344
66
169344
67
169344
68
169344
69
169344
70
169344
71
169344
72
169344
73
169344
74
169344
75
169344
76
169344
77
169344
78
169344
79
169344
80
169344
81
169344
82
169344
83
169344
84
169344
85
169344
86
169344
87
170496
88
170496
89
170496
90
170496
91
170496
92
170496
93
170496
94
170496
95
170496
96
170496
97
170496
98
170496
99
170496
100

In [ ]:
len(test_audio)

110

In [ ]:
mfccs=[]
for j in range(0,110):
  mfcc1=mfcc(signals[j],rate[j],winlen=0.1,winfunc=np.hamming,winstep=0.05,numcep=13,appendEnergy=True,highfreq=8000)
  print(np.shape(mfcc1))
  delta=librosa.feature.delta(mfcc1)
  accerlation=librosa.feature.delta(mfcc1,order=2)
  print(np.shape(delta))
  print(np.shape(accerlation))
  print("\n")
  mfcc1=np.append(mfcc1,delta,axis=1)
  mfcc1=np.append(mfcc1,accerlation,axis=1)
  mfccs.append(mfcc1)

In [ ]:
np.save('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/mfccs_test.npy',mfccs)

/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [ ]:
max=0
for i in mfccs:
  if max<np.shape(i)[0]:
    max=np.shape(i)[0]

In [ ]:
max

154

In [ ]:
b=np.load('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/mfccs.npy',allow_pickle=True)

In [ ]:
max_train=0
for i in b:
  if max_train<np.shape(i)[0]:
    max_train=np.shape(i)[0]

In [ ]:
max_train

157

In [ ]:
pad=np.zeros((157,39))

In [ ]:
pad_mfccs=[]
for i in mfccs:
  pad=np.zeros((157,39))
  pad[:np.shape(i)[0],:np.shape(i)[1]] = i
  pad_mfccs.append(pad)
  

In [ ]:
pad_train_mfccs=[]
for i in b:
  pad=np.zeros((157,39))
  pad[:i.shape[0],:i.shape[1]] = i
  pad_train_mfccs.append(pad)
  


In [ ]:
np.shape(pad_test_mfccs[1])

(157, 39)

In [ ]:
len(pad_mfccs)

110

In [ ]:
np.save('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/pad_train.npy',pad_train_mfccs)

In [ ]:
np.save('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/pad_test.npy',pad_mfccs)

In [ ]:
np.shape(pad_train_mfccs)

(0,)

In [7]:
import tensorflow as tf

In [8]:
import keras

In [23]:
input=tf.keras.Input(shape=(157,39))
normalised=tf.keras.layers.BatchNormalization()(input)
mask=tf.keras.layers.Masking()(normalised)
lstm=tf.keras.layers.LSTM(39,recurrent_dropout=0.3,return_sequences=True)(mask)
self_attention=SeqSelfAttention(attention_type=SeqSelfAttention.ATTENTION_TYPE_MUL)(lstm)
multi_head=tf.keras.layers.MultiHeadAttention(num_heads=2, key_dim=2)(self_attention,self_attention)
gap=tf.keras.layers.GlobalAveragePooling1D()(multi_head)
fc1=tf.keras.layers.Dense(80,activation=fastGELU)(gap)
norm1=tf.keras.layers.BatchNormalization()(fc1)
d1=tf.keras.layers.Dropout(0.3)(norm1)
fc2=tf.keras.layers.Dense(80,activation=fastGELU)(d1)
norm2=tf.keras.layers.BatchNormalization()(fc2)
d2=tf.keras.layers.Dropout(0.3)(norm2)
result=tf.keras.layers.Dense(3,activation=tf.keras.activations.softmax)(d2)
model = keras.models.Model(inputs=[input], outputs=[result])
model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3,decay=1e-6),
    loss=tf.keras.losses.CategoricalCrossentropy(),
    metrics=[tf.keras.metrics.CategoricalAccuracy(),tf.keras.metrics.Recall(),tf.keras.metrics.Precision(),tfa.metrics.F1Score(num_classes=3)]
)
model.summary(line_length=100)


Model: "model"
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
input_1 (InputLayer)             [(None, 157, 39)]     0                                            
____________________________________________________________________________________________________
batch_normalization (BatchNormal (None, 157, 39)       156         input_1[0][0]                    
____________________________________________________________________________________________________
masking (Masking)                (None, 157, 39)       0           batch_normalization[0][0]        
____________________________________________________________________________________________________
lstm (LSTM)                      (None, 157, 39)       12324       masking[0][0]                    
____________________________________________________________________________

In [5]:
!pip install keras-self-attention
from keras_self_attention import SeqSelfAttention
!pip install keras-multi-head
from keras_multi_head import MultiHead
from sklearn.metrics import fbeta_score
from keras import backend as K

  Created wheel for keras-self-attention: filename=keras_self_attention-0.49.0-cp36-none-any.whl size=19468 sha256=9de6ac75534f5906b9ec027dde9ac9124cd2006fb9b6a68c8fe546d40c85be44
  Stored in directory: /root/.cache/pip/wheels/6f/9d/c5/26693a5092d9313daeae94db04818fc0a2b7a48ea381989f34
Successfully built keras-self-attention
  Created wheel for keras-multi-head: filename=keras_multi_head-0.27.0-cp36-none-any.whl size=15612 sha256=7e69e87d546b4d67b1ed9b60659b30642557fac4cad958f577fe7632979b0bbd
  Stored in directory: /root/.cache/pip/wheels/b5/b4/49/0a0c27dcb93c13af02fea254ff51d1a43a924dd4e5b7a7164d
  Created wheel for keras-self-attention: filename=keras_self_attention-0.46.0-cp36-none-any.whl size=17278 sha256=73e4734bc76e1cfc15d3a0f4e3c0b15d219951d3a88a7b952fc2c081ac7a2a5d
  Stored in directory: /root/.cache/pip/wheels/d2/2e/80/fec4c05eb23c8e13b790e26d207d6e0ffe8013fad8c6bdd4d2
Successfully built keras-multi-head keras-self-attention
  Found existing installation: keras-self-attentio

In [9]:
@tf.function
def fastGELU(x):
    return tf.math.maximum(0.,tf.math.minimum(1.,((1.702*x+1)/2)))*x

In [10]:
import tensorflow_addons as tfa

In [11]:
y_train=np.load('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/y_train.npy')

In [12]:
x_train=np.load('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/pad_train.npy')

In [32]:
model.fit(x=x_train,y=y_tr,epochs=130,batch_size=10)

Epoch 1/130
25/25 [==============================] - 4s 102ms/step - loss: 0.1274 - categorical_accuracy: 0.9440 - recall: 0.9400 - precision: 0.9438 - f1_score: 0.9448
Epoch 2/130
25/25 [==============================] - 2s 100ms/step - loss: 0.0406 - categorical_accuracy: 0.9920 - recall: 0.9920 - precision: 0.9960 - f1_score: 0.9921
Epoch 3/130
25/25 [==============================] - 3s 102ms/step - loss: 0.0780 - categorical_accuracy: 0.9800 - recall: 0.9800 - precision: 0.9800 - f1_score: 0.9801
Epoch 4/130
25/25 [==============================] - 2s 99ms/step - loss: 0.0435 - categorical_accuracy: 0.9960 - recall: 0.9960 - precision: 0.9960 - f1_score: 0.9961
Epoch 5/130
25/25 [==============================] - 3s 101ms/step - loss: 0.0992 - categorical_accuracy: 0.9720 - recall: 0.9720 - precision: 0.9720 - f1_score: 0.9723
Epoch 6/130
25/25 [==============================] - 2s 100ms/step - loss: 0.0653 - categorical_accuracy: 0.9840 - recall: 0.9840 - precision: 0.9840 - f1_s

In [ ]:
np.shape(x_train)

(250, 157, 39)

In [30]:
y_tr=np.array(y_tr)

In [33]:
x_test=np.load('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/pad_test.npy')

In [34]:
y_test=model.predict(x_test)

In [ ]:
np.shape(y_test)

(110, 3)

In [35]:
predictions=np.argmax(y_test, axis=1) 

In [36]:
test_audio=glob.glob('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/TEST/*')

In [37]:
test_names=[]
for i in test_audio:
  test_names.append(i.split(sep="/")[6])

In [39]:
emoz=['Negative','Neutral','Positive']

In [40]:
test_csv_list=[]
for i in range(0,110):
  temp=[]
  temp.append(test_names[i])
  temp.append(emoz[predictions[i]])
  test_csv_list.append(temp)

In [41]:
df1 = pd.DataFrame(test_csv_list, columns = ['Filename', 'Class'])

In [42]:
df1.to_csv('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/test.csv',index=False)

In [43]:
df2=pd.read_csv('/content/drive/MyDrive/hacknitp_winter_21_ai_challenge-dataset/test.csv')

In [ ]:
emoz=['Negative','Neutral','Positive']

In [44]:
df2

Filename     Class
0    142.wav   Neutral
1     15.wav  Positive
2     72.wav  Positive
3    143.wav   Neutral
4    345.wav  Negative
..       ...       ...
105  312.wav  Negative
106  182.wav   Neutral
107  348.wav  Negative
108   23.wav  Positive
109  239.wav   Neutral

[110 rows x 2 columns]